// AREAS
export const FETCHING_AREAS = 'FETCHING_AREAS'
export const FETCHED_AREAS_SUCCESS = 'FETCHED_AREAS_SUCCESS'
export const FETCHED_AREAS_ERROR = 'FETCHED_AREAS_ERROR'
export const ADD_AREA = 'ADD_AREA'

// HOSTS
export const FETCHING_HOSTS = 'FETCHING_HOSTS'
export const FETCHED_HOSTS_SUCCESS = 'FETCHED_HOSTS_SUCCESS'
export const FETCHED_HOSTS_ERROR = 'FETCHED_HOSTS_ERROR'
export const ADD_HOST = 'ADD_HOST'
export const ACTIVATE_HOST = 'ACTIVATE_HOST'
export const ACTIVATE_ALL_HOSTS = 'ACTIVATE_ALL_HOSTS'
export const DECOMISSION_HOST = 'DECOMISSION_HOST'
export const DECOMISSION_ALL_HOSTS = 'DECOMISSION_ALL_HOSTS'
export const CHANGE_HOST_AREA = 'CHANGE_HOST_AREA'

// LOGS
export const FETCHING_LOGS = 'FETCHING_LOGS'
export const FETCHED_LOGS_SUCCESS = 'FETCHED_LOGS_SUCCESS'
export const FETCHED_LOGS_ERROR = 'FETCHED_LOGS_ERROR'
export const ADD_LOG = 'ADD_LOG'

// SELECTED HOST
export const SELECT_HOST = 'SELECT_HOST'
